name: collect system information
on: 
# ex√©cution manuelle
    workflow_dispatch:

jobs:
    network-and-system:
        runs-on: ubuntu-latest
        steps:
            - name: general information
              run: hostnamectl
            - name: IP address
              run: ip -4 a
            - name: identity
              run: who am i


