name: CD C
on: 
  workflow_run:
    workflows: ["CICD Clanguage"]
    types:
      - completed

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
      packages: write
# S'exécute uniquement sur les tags et si la compilation a réussi
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    steps:
      - name: sysinfo checkout
        uses: actions/checkout@v6
      - name: sysinfo download artifacts
        uses: actions/download-artifact@v6
        with:
          name: sysinfo-${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }} 
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: sysinfo
          draft: false
          generate_release_notes: true
          tag_name: ${{ github.event.workflow_run.head_branch }}
