name: CICD Clanguage
on: 
  push:
    branches:
      - 'feature/**'
    tags:
      - 'v*.*.*'

jobs:
    C-lint-sysinfo:
      if: startsWith(github.ref, 'refs/heads/feature/')
      runs-on: ubuntu-latest
      steps:
            - name: sysinfo checkout
              uses: actions/checkout@v6
            - name: sysinfo lint
              run: make lint
              
    C-compilation-sysinfo:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read
          attestations: write 
        needs: C-lint-sysinfo
        # S'exécute si le lint a réussi OU s'il a été skippé (cas des tags)
        if: |
          always() &&
          (needs.C-lint-sysinfo.result == 'success' || needs.C-lint-sysinfo.result == 'skipped') &&
          (startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/tags/v'))
        steps:
            - name: sysinfo checkout
              uses: actions/checkout@v6
            - name: sysinfo compilation
              run: make build
            - name: Generate attestation
              uses: actions/attest-build-provenance@v1
              with:
                subject-path: 'sysinfo'
            - name: sysinfo upload artifacts
              uses: actions/upload-artifact@v4
              with:
                path: sysinfo
                name: sysinfo-${{ github.sha }}              
    
    C-run-sysinfo:
        if: startsWith(github.ref, 'refs/heads/feature/')
        runs-on: ubuntu-latest
        needs: C-compilation-sysinfo
        steps:
            - name: sysinfo checkout
              uses: actions/checkout@v6
            - name: sysinfo download artifacts
              uses: actions/download-artifact@v6
              with:
                name: sysinfo-${{ github.sha}}
            - name: run sysinfo
              run: |
                 chmod +x sysinfo
                 ./sysinfo
